SET IDENTITY_INSERT [dbo].[Leveranciersbestand] ON
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (1, N'Centric                                                                                                                                                                                                                                                        ', 15059, N'Maaike Verbeek                                                                                                                                                                                                                                                 ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (2, N'Microsoft                                                                                                                                                                                                                                                      ', 18048, N'Sylvan Steen                                                                                                                                                                                                                                                   ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (3, N'Ivanti                                                                                                                                                                                                                                                         ', 37377, N'Lars Herregraven                                                                                                                                                                                                                                               ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (4, N'Master IT Solutions                                                                                                                                                                                                                                            ', 38647, N'Ad Verbeek                                                                                                                                                                                                                                                     ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (5, N'Adobe                                                                                                                                                                                                                                                          ', 37378, N'Abe de Vries                                                                                                                                                                                                                                                   ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (6, N'Snow Software                                                                                                                                                                                                                                                  ', 37379, N'Roy van Elshout                                                                                                                                                                                                                                                ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (7, N'TrendMicro                                                                                                                                                                                                                                                     ', 12348, N'Eric Woelders                                                                                                                                                                                                                                                  ')
INSERT INTO [dbo].[Leveranciersbestand] ([Id], [Leveranciersnaam], [Relatienummer], [Contactpersoon]) VALUES (8, N'VMware                                                                                                                                                                                                                                                         ', 12347, N'Marie Verhaar                                                                                                                                                                                                                                                  ')
SET IDENTITY_INSERT [dbo].[Leveranciersbestand] OFF
